kind: Service
apiVersion: v1
metadata:
  name: mapreduce-master
spec:
  selector:
    app: mapreduce-master
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: mapreduce-master
  labels:
    app: mapreduce-master
spec:
  containers:
  - name: mapreduce-master
    image: temakozyrev/mapreduce:1.14
    ports:
    - containerPort: 8080
      name: mapper
    env:
    - name: TYPE
      value: "MASTER"
    - name: MAPPER_HOST
      value: "mappers"
    - name: REDUCER_HOST
      value: "reducers"
    - name: MAPPER_PORT
      value: "8080"
    - name: REDUCER_PORT
      value: "8080"
